### ISSUE TITLE
Upgrade check should not include unstable releases

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#106]
IDEA: when checking for updates, we should only consider stable releases. (i.e. excluding alpha or beta releases)

**Comment by nxnfufunezn** [comment]
can I take this up ?

**Comment by sungwoncho** [comment]
@nxnfufunezn sure. Please have a look at 

https://github.com/dnote/cli/blob/master/core/upgrade.go#L45-L67

**Comment by sungwoncho** [comment]
Fixed in [v0.8.5](https://github.com/dnote/dnote/releases/tag/cli-v0.8.5).
