### ISSUE TITLE
Determine JSON schema for ejection.

### ISSUE THREAD

**Issue by michielboekhoff** [dnote/dnote#113]
Relevant to our discussion in #84. In order to make a new tool that ejects the SQLite database, we should first establish a JSON schema that we'd like to eject it _to_. 

I favour going with the current JSON format, as this would allow people to eject from a newer version of dnote and use the data in an older, pre-SQLite version. This backward-compatibility would not be guaranteed as the data model can change at any time. We can also introduce a compat-mode into the tool to cull any "new" attributes so that we cover this use-case.

**Comment by sungwoncho** [comment]
After some time, I think that I was too quick to make such proposal in #84.

First of all, sqlite is a pretty good format to store notes for long-term.

[The official page](https://www.sqlite.org/aff_short.html) says:

> SQLite database files are recommended by [the US Library of Congress](https://www.sqlite.org/locrsf.html) as a storage format for long-term preservation of digital content. 

And the format is far from proprietary, as sqlite exists in the public domain. Therefore I think that 'ejecting' to JSON is unlikely to provide any value to the users.

I will close this for now.
