### ISSUE TITLE
Release on arch linux

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#125]
* Allow dnote to be installed using `pacman`
* How can I automate release?

**Comment by michielboekhoff** [comment]
See [here](https://wiki.archlinux.org/index.php/creating_packages)

Pacman archives are no more than tar files. You can decide to host your own repository, or submit dnote to the official repos. The latter might have somewhat of a delay, but the former costs money.

**Comment by sungwoncho** [comment]
The server and CLI are distributed on AUR.

https://aur.archlinux.org/packages/dnote-cli-bin/
https://aur.archlinux.org/packages/dnote-server-bin/
