### ISSUE TITLE
when editor is not installed, `add` silently fails

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#191]
To reproduce, configure your editor to a program that does not exist in your PATH. (configuration is in `~/.dnote/dnoterc`). Then, run `dnote add blah`.

**Comment by ilmanzo** [comment]
Hi, I tried to reproduce this issue, but I get a nice error message saying that the editor can't be run:

```
$ dnote version
dnote 0.8.0

$ cat $HOME/.dnote/dnoterc
editor: nonexistent

$ dnote add foobar
  ⨯ Failed to get editor input: launching an editor: exec: "nonexistent": executable file not found in $PATH
```

**Comment by sungwoncho** [comment]
@ilmanzo You're right. I cannot reproduce anymore on Linux. What operating system are you on?

**Comment by ilmanzo** [comment]
Linux also for me

**Comment by sungwoncho** [comment]
Closing because it cannot be reproduced anymore. Thanks for your help.
