### ISSUE TITLE
404 when downloading via Homebrew

### ISSUE THREAD

**Issue by jamesa** [dnote/dnote#202]
* version: v0.8.0
* project (e.g. CLI): CLI
* operating system: Mac OSX 10.14.5

## Description

There is a 404 error when trying to install via Homebrew - I think because the release names on Github do not match what Homebrew expects. The releases here are prefixed with "cli-" and Homebrew does not add that same prefix when finding the download URL. I'm not sure if the fix is to change the release names on this repo or to update the Homebrew script to use this prefix.

Homebrew expected: https://github.com/dnote/dnote/releases/download/v0.8.0/dnote_0.8.0_darwin_amd64.tar.gz
Actual location: https://github.com/dnote/dnote/releases/download/cli-v0.8.0/dnote_0.8.0_darwin_amd64.tar.gz

## Steps to reproduce

```
$ brew tap dnote/dnote
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask-versions and homebrew/cask).
No changes to formulae.

==> Tapping dnote/dnote
Cloning into '/usr/local/Homebrew/Library/Taps/dnote/homebrew-dnote'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Tapped 1 formula (34 files, 27.9KB).
```
```
$ brew install dnote
Updating Homebrew...
==> Installing dnote from dnote/dnote
==> Downloading https://github.com/dnote/cli/releases/download/v0.8.0/dnote_0.8.0_darwin_amd64.tar.gz
==> Downloading from https://github.com/dnote/dnote/releases/download/v0.8.0/dnote_0.8.0_darwin_amd64.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "dnote"
Download failed: https://github.com/dnote/cli/releases/download/v0.8.0/dnote_0.8.0_darwin_amd64.tar.gz
```

**Comment by sungwoncho** [comment]
I have fixed it. Sorry about that. Please try again, and feel free to re-open.

**Comment by jamesa** [comment]
Looks good now, thanks!
