### ISSUE TITLE
dnote.io website bug

### ISSUE THREAD

**Issue by estysdesu** [dnote/dnote#215]
Love the app and the idea. Really considering subscribing or self hosting.
* project/version (e.g. CLI v0.8.0): n/a
* operating system: n/a

## Description
First, the pro subscription signup has a different style than the free source code button. I'm sure this was intentional to put emphasis on the pro signup over the free, but I don't think this you want it to look like this. ![this](https://user-images.githubusercontent.com/37026871/60379300-b88df500-9a6b-11e9-9afa-79b24da3569b.png)

Second, likely related, when going to inspect it, I noticed the order of pro and free boxes swap places. That maybe be intentional. However, the button no longer shows up in responsive/mobile views to sign up for the pro subscription in the pro box. ![button no longer shows up](https://user-images.githubusercontent.com/37026871/60379290-7fee1b80-9a6b-11e9-916b-28d507d58f7a.png) ![button no longer shows up](https://user-images.githubusercontent.com/37026871/60379359-bd06dd80-9a6c-11e9-9761-ed9c1dab4050.png)

I think it's due to the `type=button` tag on the pro button. Once toggling off, the button shows up again.
![button shows up again](https://user-images.githubusercontent.com/37026871/60379344-80d37d00-9a6c-11e9-94b0-e7fb6836cc4b.png)

```
<a id="T-unlock-pro-btn" type="button" class="button button-normal button-third button-stretch" href="/app/subscriptions/checkout">Unlock</a>
```

## Steps to reproduce
1. Sign up for dnote.io
2. Click "Get Started"

**Comment by estysdesu** [comment]
Follow up, maybe unrelated, question. You mention self hosting. But, it doesn't seem like you mean being able to self-host on anything like AWS. Is it only able to be hosted locally and on dnote.io? 

If self hosting is possible (on something like AWS), how would I access the web view of dnote. Would it just be `<my-hosted-ip-address>/app`. How would I deploy, I'm not seeing any go binaries that support being a host or any other instructions?

**Comment by sungwoncho** [comment]
Hi @estysdesu, thanks for the detailed bug report. Despite the steps kindly provided, I was not able to reproduce the bug on Firefox 67.0.2 and chrome 75.0.3770.100. Could you specify your OS/browser version and also check if you have any addons that might be affecting the style/presentation?

The button should look like the purple one presented in your final screenshot. It's indeed odd that `type="button"` is causing that. It seems to have a good [browser support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Browser_compatibility).

Anyway, once I get more information about your runtime, I will try to reproduce again.

**Comment by sungwoncho** [comment]
For the self-hosting question: at the moment I am yet to officially document steps to self-host. I am doing [some ground works](https://forum.dnote.io/t/dnote-live-coding-session-14-road-to-self-hosting/24) to make that happen. Basically #186 and #201 were the biggest pieces of work, and a good news is that they are implemented in `master` as of today. Soon I will cut a new release, and come up with an official self-host guideline that I will support.

You will be able to access Dnote web app on `<my-hosted-ip-address>`. Also, endpoints will be configurable from `dnoterc` file thanks to #213. It hasn't been released yet. I will try to provide a self-hosting guideline in the next release.

**Comment by estysdesu** [comment]
OS: MacOS 10.14.5
Browser: Chrome Stable -- Version 75.0.3770.100 (Official Build) (64-bit)
Extensions: Vimium, Better Go Playground, NordVPN -- 2 of these do in fact affect css styles
URL: https://dnote.io/app/subscriptions
Steps: same as noted above

After disabling all extensions, hard restarting chrome, and clear cache with a hard reload, I'm seeing the same results. Maybe it's a fluke somehow. If I'm the only one who has reported, it's possible it's an isolated event even though I don't know what could be causing it.

**Comment by estysdesu** [comment]
Wow, that's great news on the self hosted docs and ground work you've laid for it! I look forward to playing with it! Again, really love the project. I've been on the hunt for a better way to keep track of my notes cross platform with something that looked sleek and had organization (tags or folders (books in this case) and the console app is indeed a bonus. 

Also, I'm impressed your price is so reasonable. Compared to if someone were to run **only** the dnote app on a server it would likely cost at least that on a micro container in addition to handling maintenance. 

Last question. Do you have any way of exporting data. Say I have hundreds of notes currently stored on dnote. Have you created a tool that can export note content say if someone wanted to quit their subscription.

**Comment by estysdesu** [comment]
After doing some digging, I think I may have found the issue? With the msdn link you provided, that refers to the button element, not the type. If you look at [this](https://www.w3schools.com/tags/att_type.asp) page on w3, it mentions which tags support the type attribute and they don't mention the anchor tag. Then if you look [here](https://www.w3schools.com/tags/tag_a.asp) you can see it does support the type attribute, but only for `media_type` which `button` is not. I know msdn is more of the trusted resource than w3, but they don't list which elements/tags can have the type attribute. But, if you're seeing it on your browser with the same version as mine, I'm a little confused. 

All I can say is that when I change the html element to button `<button>` (which certainly supports `type=button`) instead of anchor `<a>` tags, the button shows exactly as I'd expect. 
![image](https://user-images.githubusercontent.com/37026871/60381477-601d1e80-9a90-11e9-86cb-50e58e324ac7.png)

**Comment by sungwoncho** [comment]
@estysdesu that makes sense. I mistakenly wrote an invalid HTML and it seems like macOS Chrome is a bit unforgiving. The culprit is the following. If you would like to do a PR. You can just remove `type="button"`. Otherwise I might fix it up tomorrow.

 https://github.com/dnote/dnote/blob/35dc7abfae2a046d59abb9a3b90d82d6e86b30f4/web/src/components/Subscription/index.js#L166 

Thanks for the feedback. I've also been digging if it is possible to ship desktop/Android/iOS app using the same JS+Go codebase and the result have been promising so far.

As for exporting data, I think that any note-taking software should be [local-first, open source, and store the data in non-proprietary format](https://dnote.io/blog/how-i-built-personal-knowledge-base-for-myself/#a-knowledge-base-needs-to-be-local-first-and-open-source). The reason is that businesses come and go, but our knowledge needs to live on.

Dnote already stores all user data locally in users' computers in SQLite which is in public domain, and is [recommended](https://www.sqlite.org/aff_short.html) for long-term preservation of digital content. So users can just stop using Dnote Pro and keep all their notes without having to 'export' the data. Additionally, because of end-to-end encryption, the server has zero knowledge about what user has actually written thus far.

It is getting long so I can answer any further questions on the [forum](https://forum.dnote.io/).

**Comment by estysdesu** [comment]
Thanks for the opportunity to contribute!
