### ISSUE TITLE
Not able to enter password for login

### ISSUE THREAD

**Issue by mind-e-00** [dnote/dnote#219]
I am using dnote_0.8.2 and have tried to login but unable to enter my password. The question mark does not turn green such as the username line. Pressing enter results in the following line being returned:

logging in: requesting session: making http request: server responded with an error: response 401 "Wrong email and password combination"

**Comment by sungwoncho** [comment]
Unfortunately I was not able to reproduce the issue on Window 10 Powershell and Command Prompt. I assumed your OS based on your previous issue #218. If my assumption is wrong, please provide more information.

The password input is supposed to be muted, and you won't be able to see the password as you type. The question mark is not supposed to turn green, indicating that the input is muted. If that UI decision is confusing to you, I am happy to receive a feedback.

Could you try typing your password as you normally would in spite of the muted input? Alternatively copy and pasting also works.

**Comment by sungwoncho** [comment]
@mind-e-00 could you tell me if you are still having the issue?

**Comment by sungwoncho** [comment]
@mind-e-00 I will close this issue due to inactivity. Please feel free to re-open if you continue to experience it.
