### ISSUE TITLE
Would love to try using on windows

### ISSUE THREAD

**Issue by nomatica** [dnote/dnote#259]
Local install on windows would be great.  Thanks

**Comment by sungwoncho** [comment]
Hi @nomatica, Windows executable is included in releases.

* Could you try https://github.com/dnote/dnote/releases/tag/cli-v0.10.0?
* Are you looking for something like an automated installation process for Windows?

**Comment by nomatica** [comment]
Sorry for the delay. Yes, I  was looking for something with an automated windows installation process.

**Comment by sungwoncho** [comment]
No worries. I understand where you are coming from. In fact, this discussion came up in #218 as well. I have opened #264 to collect feedback. Let's continue the discussion over there.
