### ISSUE TITLE
Contributor guide is incomplete for Windows users

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#269]
## Environment

* project (cli, server, browser-extension): all
* version: N/A
* operating system: Windows

## Description

Fix the `CONTRIBUTING.md` to completely doucment setup/development process for Windows users. The example issues are as follows:

* On some machines, `make` is not available.
* Explain how to set the url of the repository to the fork.
* `make` fails with " abnormal program termination"
* Document installing `git`

## Steps to reproduce

* Follow `CONTRIBUTING.md`

**Comment by LandonLoo** [comment]
I am trying to work on it.

**Comment by sungwoncho** [comment]
Thanks @LandonLoo for pairing with me to tackle this one. This will be solved by #272.
