### ISSUE TITLE
Make self-hosting easier

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#275]
* **Please describe the feature you would like to have.**
A more automated way to self-host Dnote

* **What alternatives have you considered?**
N/A

* **Any additional context**

Currently [the self hosting guide](https://github.com/dnote/dnote/blob/master/SELF_HOSTING.md) involves a lot of steps. Those steps should be automated to make self-hosting easier.

IDEA:

* Configuration management tools such as Ansible
* Bash script

Feedback welcomed.

**Comment by clinta** [comment]
An official docker container would make this much easier to get started.

**Comment by sungwoncho** [comment]
@clinta Thanks for your thoughtful suggestion. Now there is the [official docker image](https://hub.docker.com/repository/docker/dnote/dnote) and an [installation guide](https://github.com/dnote/dnote/blob/master/host/docker/README.md). I will leave this issue open to take further suggestions.

**Comment by cocoonkid** [comment]
This is great. Thumbs up!

**Comment by sungwoncho** [comment]
Closing this because we now publish the official docker image.
