### ISSUE TITLE
Allow to set smtp port on server

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#277]
* **Please describe the feature you would like to have.**
Currently it seems like the port for the smtp connection is 465 is hardcoded. My smtp server only supports port 587 (with STARTLS) so I was wondering if it could be made possible to configure

**Comment by sungwoncho** [comment]
Thanks for your patience. You can now specify an environment variable `SmtpPort` from [v0.2.1](https://github.com/dnote/dnote/releases/tag/server-v0.2.1). Here is a [CHANGELOG](https://github.com/dnote/dnote/blob/master/CHANGELOG.md#upgrade-guide).
