### ISSUE TITLE
links in email verification email does not go to self-hosted server

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#278]
## Environment

* project (cli, server, browser-extension): server
* version: 0.1.1
* operating system: ubuntu 16.04 

## Description
The self-hosted server can send out the verification email, but the links in the mail links to the app.getdnote.com domain and not the self-hosted server. 

## Steps to reproduce
send verification mail from selfhosted server - check links in email

**Comment by kimusan** [comment]
... replacing the domain in the links with the selfhosted server domain and the link works correctly.

**Comment by mzch** [comment]
Hi,
There are some hard-coded links in the source code.
Can you replace it with a configurable value as an environment variable?

**Comment by sungwoncho** [comment]
@kimusan @mzch Thanks for the report and your patience. It was fixed in [v0.2.1](https://github.com/dnote/dnote/releases/tag/server-v0.2.1). Please see the [upgrade instruction](https://github.com/dnote/dnote/blob/master/CHANGELOG.md#upgrade-guide).
