### ISSUE TITLE
Make it possible to use browser extension with selfhosted server

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#279]
* **Please describe the feature you would like to have.**
Currently there is not way (at least that I have found) to change the server used by the browser extension. It would be nice if it was possible so it can be used with self-hosted servers.

**Comment by sungwoncho** [comment]
Thanks for requesting the feature. I see two possible solutions:

1. Allow to set endpoints in a browser extension through UI.
2. Add a flag in the build to override endpoints during the build time.

What do you think? In the meantime, you can get around it by overriding these values in the webpack configuration:

https://github.com/dnote/dnote/blob/1250825578f2ceb99fa2cfa1265d4ea9665d3eba/browser/webpack.config.js#L38-L39

**Comment by kimusan** [comment]
I would personnally prefer solution 1 as this would make it possible to use the extension from the appstore and thereby get easy access to it from all devices.

**Comment by kimusan** [comment]
tried building the browser extension in Linux (Ubuntu) but it did not work.  Some npm requirements were not met. 
npm install
dnote-extension@1.1.1 /home/kschulz/repo/dnote/browser
├── eslint@6.5.1  extraneous
├── UNMET PEER DEPENDENCY eslint-plugin-react-hooks@2.2.0
└── history@4.10.1  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-react-hooks@^1.7.0 but none was installed.
npm WARN dnote-extension@1.1.1 No repository field.
npm WARN dnote-extension@1.1.1 license should be a valid SPDX license expression


The "history" module is also not installed by "npm install" but I had to install it manually.

**Comment by sungwoncho** [comment]
@kimusan good idea. I will implement solution 1 and keep this issue open so that you can track progress. In the meantime, please build manually. Sorry about the dependency issue. If you continue to have problem building, please feel free to open an issue.

**Comment by kimusan** [comment]
I never got it to build. Kept hitting the dependency mess on Ubuntu linux. Not too familiar with the npm build system so I am not sure how to get around this problem.

**Comment by sungwoncho** [comment]
I see, I will get to this tomorrow. Sorry about that.

**Comment by sungwoncho** [comment]
I can confirm that I get the following error while building the extension

```
[0] ERROR in /home/sung/dev/go/src/github.com/dnote/dnote/jslib/src/helpers/url.ts
[0] [tsl] ERROR in /home/sung/dev/go/src/github.com/dnote/dnote/jslib/src/helpers/url.ts(22,26)
[0]       TS2307: Cannot find module 'history'.
[0]
[0] ERROR in /home/sung/dev/go/src/github.com/dnote/dnote/jslib/src/helpers/queries.ts
[0] [tsl] ERROR in /home/sung/dev/go/src/github.com/dnote/dnote/jslib/src/helpers/queries.ts(19,26)
[0]       TS2307: Cannot find module 'history'.
```

The fix is to run `make install-js` from the project root, then run `./scripts/build.sh` in `browser` directory again. The reason is that `browser` project depends on `jslib` project, and `jslib` project depends on `history`.

Hope this helps as an interim solution.

**Comment by kimusan** [comment]
Works like a charm - thanks for the fix.
