### ISSUE TITLE
Add server version number somewhere in webUI

### ISSUE THREAD

**Issue by kimusan** [dnote/dnote#283]
* **Please describe the feature you would like to have.**
I just upgraded my server to the 0.2.0 version (nice work by the way) but there isn't really any way to tell if I am running the old or the new version (This time I could check by verifying that newline means newline in the preview). 
I would like to propose that a version number is shown somewhere in the webUI - e.g. in the footer, an about page under settings or alternatively as a comment in the source

**Comment by sungwoncho** [comment]
That is a great idea. It is now implemented in [v0.2.1](https://github.com/dnote/dnote/releases/tag/server-v0.2.1).
