### ISSUE TITLE
Aborted due to panic

### ISSUE THREAD

**Issue by mzch** [dnote/dnote#307]
## Environment

* project (cli, server, browser-extension): server
* version: 0.3.0
* operating system: Debain 10 (Buster)

## Description
Dnote server aborted at startup.

```
Nov 12 12:41:03 Macmini dnote-server[4590]: panic: initializing weekly digest template: reading template: stat /srv/dnote/templates/src/digest.html: no such file or directory
```
I read CHANGELOG.md but I couldn't find related things.

## Steps to reproduce
exec `dnote-server start`

**Comment by sungwoncho** [comment]
Sorry about that. It has been fixed in [v0.3.1](https://github.com/dnote/dnote/releases/tag/server-v0.3.1). I will implement a smoke test using a VM and integrate it into the release process. Please re-open if the issue persists.
