### ISSUE TITLE
Allow to add a pro user for self-hosting

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#318]
* **Please describe the feature you would like to have.**
Allow to add a pro user for self-hosted instances.

* **What alternatives have you considered?**

* **Any additional context**
Currently, self-hosted users need to run a SQL query manually in order to upgrade the user they have registered:

```
UPDATE users SET cloud = true FROM accounts WHERE accounts.user_id = users.id AND accounts.email = '$yourEmail';
```

There are two ways to improve the user experience:

1. The web application should register the account as pro account if the Dnote is self-hosted.
2. Add a sub-command in `dnote-server` prograrm to allow to register a new user. e.g. `dnote-server add-user me@example.com password`

**Comment by Bhudjo** [comment]
Thanks for your project. 
Only a minor point, the ui doesn't show that you're _pro_ (or maybe in this case, _self-hosted_) therefore everything is already unlocked.
Maybe it's worth to have it in the ui.

**Comment by sungwoncho** [comment]
@Bhudjo, good idea. I think we can either:

* stop displaying the billing section in the settings, because it is irrelevant and confusing.
* hack the billing section to display pro plan if self-hosted.

I think the first solution is simple and makes sense.

**Comment by sungwoncho** [comment]
@Bhudjo thanks for your input. From [v1.0.4](https://github.com/dnote/dnote/releases/tag/server-v1.0.4), on-premise versions ship without the billing related user interface to reduce cognitive overhead and simplify the experience.

**Comment by qaqland** [comment]
>     2. Add a sub-command in `dnote-server` prograrm to allow to register a new user. e.g. `dnote-server add-user me@example.com password`

how is it this going? i want to create user for self-host.

**Comment by sungwoncho** [comment]
@qaqland, for self-hosted Dnote, all users are upgraded to pro automatically. There is no action required.
