### ISSUE TITLE
ARM64v8 ?

### ISSUE THREAD

**Issue by fredix** [dnote/dnote#319]
Hi, would you create a dnote-server compiled for ARM64v8 ? It will be awesome for my server :)
Best regards.

**Comment by sungwoncho** [comment]
Hi @fredix, it should be possible to compile for arm64. I will do some more research.

In the meantime, you can try to compile by changing the following line

https://github.com/dnote/dnote/blob/0c9670f44262852b986af532ef92d40512e6345c/scripts/server/build.sh#L66

into

```
build linux arm64
```

Feel free to replace `linux` with one of [the following](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#a-list-of-valid-goos-values).

More information about setting up is available [here](https://github.com/dnote/dnote/blob/master/CONTRIBUTING.md) in case you want to give it a go.

**Comment by sagidayan** [comment]
Also looking into this - changing this line in the build.sh file does not help.
Would be great if you can create a docker image for `arm` and `arm64`.

**Comment by sungwoncho** [comment]
@fredix @sagidayan Dnote server official release now includes a binary for arm64. Thanks for your request.

I will start building docker image for it once docker officially supports multi platform build ([buildx](https://github.com/docker/buildx) is still experimental).

As a bonus, Dnote CLI also officially supports arm64. Please feel free to re-open.

**Comment by sungwoncho** [comment]
@sagidayan Dnote server docker image now supports arm64 and armv7: https://hub.docker.com/layers/dnote/dnote/3.0.0-rc3/images/sha256-fd3ca1105c2972beac7685d74231f76fb8f5d26b46f6f6d4aca2818ec6d189dc It's a still rc and official release will come later.
