### ISSUE TITLE
Dnote crashes on accessing direct note link.

### ISSUE THREAD

**Issue by cocoonkid** [dnote/dnote#322]
## Environment

* project (cli, server, browser-extension): 
extension and web

* version: latest docker image
* operating system: 
docker image (ubuntu 19.10 host)

## Description
I run dnote in docker containers behind a nginx reverse proxy to deliver the letsencryt certificates on-the-fly which works with all the other things I'm self hosting.

I was able to run dnote. login from cli and login from hte browser extension.
The webb gui works as intended too. 
. When accessing the note via the webgui no errors show up, the actual URL https://dnote.brofistmedia.com/notes/c448d475-3024-4e92-a3db-79e6b7e10051?queries%5Bq%5D=&queries%5Bbook%5D=dnote

Works as intended and is properly displayed.

But upon pressing b within the chrome extension to visit a specific note the page blanks out.(502 bad gateway request).

nginx log: 

``` [error] 18#18: *1931 upstream prematurely closed connection while reading response header from upstream, client: 185.244.212.62, server: dnote.brofistmedia.com, request: "GET /notes/c448d475-3024-4e92-a3db-79e6b7e10051?queries%5Bq%5D=&queries%5Bbook%5D=dnote HTTP/2.0", upstream: "http://172.18.0.4:3000/notes/c448d475-3024-4e92-a3db-79e6b7e10051?queries%5Bq%5D=&queries%5Bbook%5D=dnote", host: "dnote.brofistmedia.com"```

dnote log:
```
2019/11/19 10:13:11 http: panic serving 172.18.0.3:54342: runtime error: invalid memory address or nil pointer dereference


goroutine 1209 [running]:


net/http.(*conn).serve.func1(0xc000424a00)


	/usr/local/go/src/net/http/server.go:1767 +0x139


panic(0x9ff800, 0x10a8640)


	/usr/local/go/src/runtime/panic.go:679 +0x1b2


github.com/jinzhu/gorm.(*DB).clone(0x0, 0xe43028f04c2f6d01)


	/home/sung/dev/go/pkg/mod/github.com/jinzhu/gorm@v1.9.9/main.go:821 +0x26


github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9ca9c0, 0xc9b6e0, 0xc0002d39a0, 0x1, 0x1, 0xc0003bc8f0)


	/home/sung/dev/go/pkg/mod/github.com/jinzhu/gorm@v1.9.9/main.go:232 +0x2f


github.com/dnote/dnote/pkg/server/handlers.AuthWithSession(0x0, 0xc00037f300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)


	/home/sung/dev/dnote-workspace/dnote/pkg/server/handlers/routes.go:132 +0x145


github.com/dnote/dnote/pkg/server/tmpl.AppShell.newNotePage(0xc00011e480, 0x0, 0xc00037f300, 0xc00007af0b, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)


	/home/sung/dev/dnote-workspace/dnote/pkg/server/tmpl/data.go:56 +0x87


github.com/dnote/dnote/pkg/server/tmpl.AppShell.getData(0xc00011e480, 0x0, 0xc00037f300, 0xc00031db00, 0x16, 0xc00004faf0, 0x414dc1, 0x160, 0xa4b600)


	/home/sung/dev/dnote-workspace/dnote/pkg/server/tmpl/app.go:80 +0xdf


github.com/dnote/dnote/pkg/server/tmpl.AppShell.Execute(0xc00011e480, 0xc00037f300, 0x0, 0xd, 0xc00042e8c8, 0xc00004faf8, 0x4c4cc7, 0x0)


	/home/sung/dev/dnote-workspace/dnote/pkg/server/tmpl/app.go:63 +0x77


github.com/dnote/dnote/pkg/server/web.getRootHandler.func1(0xcb53e0, 0xc0000d9340, 0xc00037f300)


	/home/sung/dev/dnote-workspace/dnote/pkg/server/web/handlers.go:69 +0x13c


net/http.HandlerFunc.ServeHTTP(0xc000160ee0, 0xcb53e0, 0xc0000d9340, 0xc00037f300)


	/usr/local/go/src/net/http/server.go:2007 +0x44


net/http.(*ServeMux).ServeHTTP(0xc0000669c0, 0xcb53e0, 0xc0000d9340, 0xc00037f300)


	/usr/local/go/src/net/http/server.go:2387 +0x1bd


net/http.serverHandler.ServeHTTP(0xc0000d80e0, 0xcb53e0, 0xc0000d9340, 0xc00037f300)


	/usr/local/go/src/net/http/server.go:2802 +0xa4


net/http.(*conn).serve(0xc000424a00, 0xcb6ba0, 0xc00040a4c0)


	/usr/local/go/src/net/http/server.go:1890 +0x875


created by net/http.(*Server).Serve


	/usr/local/go/src/net/http/server.go:2927 +0x38e```

**Comment by sungwoncho** [comment]
Thanks for the detailed error report. A fix was released in [0.3.2](https://github.com/dnote/dnote/releases/tag/server-v0.3.2). Docker image is available with a tag `0.3.2` or `latest`. Please feel free to reopen if the issue persists.
