### ISSUE TITLE
Add an option to disable registration

### ISSUE THREAD

**Issue by neoromantique** [dnote/dnote#358]
Currently when self hosting anyone with a link can create an account on my instance, I'd like to have an option to disallow that.

**Comment by sungwoncho** [comment]
Implemented in [v0.3.3](https://github.com/dnote/dnote/releases/tag/server-v0.3.3).

Please set `DisableRegistration` environment variable to `true`. Then the API will respond with 403 for registration requests. What do you think?

**Comment by neoromantique** [comment]
As a workaround of sorts for now -- splendid, but long-term I believe it should be toggle-able in GUI.

**Comment by neoromantique** [comment]
Closing this for now as current solution is good enough for me, thanks!

**Comment by sungwoncho** [comment]
Yeah, some sort of admin panel could be useful in the long run. Let's keep your suggestion in mind for the future.
