### ISSUE TITLE
Fix bad link on Pricing FAQ page

### ISSUE THREAD

**Issue by spiritphyz** [dnote/dnote#372]
## Environment
Dnote website pricing page:
https://www.getdnote.com/pricing/

## Description
There's a bad link under "Pricing FAQ".

The phrase "**a knowledge base should never be proprietary.**" erroneously links to localhost:
 * http://localhost:1313/blog/how-i-built-personal-knowledge-base-for-myself/#a-knowledge-base-needs-to-be-local-first-and-open-source

A proper working link should be provided instead.

**Comment by sungwoncho** [comment]
thanks for taking time to file an issue. It has been fixed.
