### ISSUE TITLE
syntax highlighting in markdown in web client

### ISSUE THREAD

**Issue by cabrrtt** [dnote/dnote#373]
## Environment

* web client 
* master 
* chrome 

## Description
Given the following markdown:
```
\\``` javascript
var foo = function (bar) {
  return bar++;
};

console.log(foo(5));
\\```
```
expect to see the rendered markdown highlighted using highlight.js. However, is just rendered as plain \<pre\> content

appears the css is missing as the HTML contains the highlight.js related markup.

**Comment by sungwoncho** [comment]
Thanks for taking time to file an issue. This has been fixed. 
The fix was also released in [v0.3.4](https://github.com/dnote/dnote/releases/tag/server-v0.3.4).

Please feel free to comment or re-open.
