### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by davep** [dnote/dnote#384]
* **Please describe the feature you would like to have.**

Not exactly a request about dnote itself, but about the dnote blog. Apologies if this could be better placed elsewhere but I couldn't see a repo to do with the website or blog.

Would it be possible to have an RSS feed added to the [dnote blog](https://www.getdnote.com/blog/)?

**Comment by sungwoncho** [comment]
Hi @davep, no worries. Let me know if the following link meets your needs: https://www.getdnote.com/blog/index.xml

Just curious, how do you intend to consume it?

**Comment by davep** [comment]
That looks great, thanks. Might be an idea to include a link to it in the `<head>` of the HTML so it's easier to discover.

> Just curious, how do you intend to consume it?

I use [The Old Reader](https://theoldreader.com/) to manage all my subscriptions, and then different clients on iOS, Android and macOS that use the tOR API to keep me in sync everywhere. And I often use the Google RSS extension in Chrome to discover feeds on pages and send the subscription request to tOR.

**Comment by sungwoncho** [comment]
Thanks for sharing.

Good idea. I have included the following in the blog:

```
<link rel="alternate" type="application/rss+xml" href="https://www.getdnote.com/blog/index.xml" title="Blog | Dnote">
```

**Comment by davep** [comment]
That works perfectly. :)
