### ISSUE TITLE
Lack of word-wrap when viewing notes

### ISSUE THREAD

**Issue by davep** [dnote/dnote#388]
## Environment

Any web browser, when viewing notes on the web (reproduced with Chrome and Safari on iOS, and Chrome on macOS).

## Description

Notes with long lines tend not to word-wrap, instead simply breaking onto the next line part way through a word. I first noticed this in the web app when viewing it via Chrome, and also Safari, on iOS. For example, look at the second paragraph here:

![file](https://user-images.githubusercontent.com/28237/71967220-e615e100-31fa-11ea-993a-3c1a6752ab50.jpeg)

A similar effect is visible in Chrome on the desktop (macOS in this case). Both when viewing in a small browser window (so giving a more mobile view):

![Screenshot 2020-01-08 at 09 36 38](https://user-images.githubusercontent.com/28237/71967354-28d7b900-31fb-11ea-850e-b8a38cdc7822.png)

And also in much wider windows too:

![Screenshot 2020-01-08 at 09 37 37](https://user-images.githubusercontent.com/28237/71967393-3725d500-31fb-11ea-99f3-c7bc3a35a990.png)

**Comment by sungwoncho** [comment]
Thanks for taking time to report an issue. It has now been fixed in [v0.4.0](https://github.com/dnote/dnote/releases/tag/server-v0.4.0) and in master. Please feel free to reopen in case it persists.

**Comment by davep** [comment]
Looking good here. Many thanks for the swift fix. :)
