### ISSUE TITLE
Uninstall instruction should be on the readme 

### ISSUE THREAD

**Issue by joaogui1** [dnote/dnote#393]
* **Please describe the feature you would like to have.**
We have readmes teaching how to install dnote in many different ways, but no instruction about uninstalling

* **What alternatives have you considered?**

* **Any additional context**
I want to know how to uninstall dnote-cli and dnote-docker

**Comment by sungwoncho** [comment]
@joaogui1 thanks for taking time to post a suggestion, and sorry for the confusion. You are not alone (#79).

Dnote CLI is a binary, and as such, you can just remove the binary from your system. For instance, using bash on Linux, you could do something like:

```bash
rm $(which dnote)
```

If you have pulled Dnote docker image, you can remove the docker image by running `docker rmi [dnote-image-name]`. More info on their [doc](https://docs.docker.com/engine/reference/commandline/rmi/).

I am not going to include uninstall instruction in README to keep it simple. There is a plan to launch a documentation website and it will incorporate your suggestion.

**Comment by joaogui1** [comment]
Thank you very much!
