### ISSUE TITLE
CLI dnote login problem 

### ISSUE THREAD

**Issue by vcg3rd** [dnote/dnote#402]
dnote login returns:

`requesting session: making http request: server responded with an error: response 401 "Wrong email and password combination"`

donotrc has `apiEndpoint: https://api.getdnote.com`

I can log in with the credentials here: https://www.getdnote.com/

Also I installed oh-my-zsh and added dnote to my zsh plugins in .zshrc and yet dnote a TAB becomes oa TAB again and it becomes /Downloads.

I have a Pro account.

**Comment by sungwoncho** [comment]
@vcg3rd sorry to hear about the issue. Let us resolve the issue with the login first, then move on to the oh-my-zsh issue.

The issue may have to do with the terminal not sending the correct credentials to the server. Could you please share your

* OS and its version
* Terminal and its version
* How you are entering the credentials (pasting, typing, backspace, etc.)

In the meantime, I will release a new version with a username and password flag so that we can bypass the credential prompt which is potentially causing the issue in this case.

**Comment by vcg3rd** [comment]
OS: Manjaro Linux x86_64 
Kernel: 5.4.15-2-MANJARO 
Shell: bash 5.0.11 

dnote 0.10.0
dnote login ---> email prompt ---> type email ---->enter
password prompt ---> type password ---> enter

Hmmm...posting that made me think about trying to login at a bash prompt, and it worked.

So I switched to zsh and got the same problem as before. zsh is zsh 5.7.1

**Comment by sungwoncho** [comment]
@vcg3rd thanks for taking time to provide additional info.

I was not able to reproduce the problem yet on Manjaro x86_64  with the kernel version 5.4.6-2-MANJARO running zsh 5.7.1.

## Solution

In the meantime, I have released [0.11.0](https://github.com/dnote/dnote/releases/tag/cli-v0.11.0) which allows you to bypass the login prompt using `--username` and `--password` flags for  the `login` subcommand. You can do:

```
dnote login --username your@email.com --password yourpassword
```

## Additional info

* Could you please try to login on zsh using `DNOTE_DEBUG=1 dnote login` and the credentials being sent are as expected? It will show the value of the email and the length of the password being sent as a login credential (see below)
* If you are signed into Dnote using bash, you should be signed in in zsh.

---

```
$ DNOTE_DEBUG=1 dnote login                                  
DEBUG: initializing the database
DEBUG: initializing the system
DEBUG: current schema: schema 12 of 12
DEBUG: Running with Dnote context: {HomeDir:/home/sung DnoteDir:/home/sung/.dnote APIEndpoint:https://api.getdnote.com Version:0.11.0 DB:0xc00000e780 SessionKey:0 SessionKeyExpiry:0 Editor:nvim Clock:0x1123c00}
  Welcome to Dnote Pro (https://www.getdnote.com).
  [?] email: john@doe.com
  [?] password: 
DEBUG: Logging in with email: john@doe.com and password: (length 12)
DEBUG: HTTP request: &{Method:POST URL:https://api.getdnote.com/v3/signin Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Cli-Version:[0.11.0]] Body:{Reader:0xc00012a0c0} GetBody:0x77afd0 ContentLength:50 TransferEncoding:[] Close:false Host:api.getdnote.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000026170}
  ⨯ logging in: requesting session: making http request: server responded with an error: response 401 "Wrong email and password combination"
```

**Comment by sungwoncho** [comment]
> Also I installed oh-my-zsh and added dnote to my zsh plugins in .zshrc and yet dnote a TAB becomes oa TAB again and it becomes /Downloads.

I was able to reproduce this on Manjaro running zsh 5.7.1. It seems like an oddity of oh-my-zsh that occurs when new plugins are added. It can be resolved by removing `.zcompdump` file in your home directory (Please see https://github.com/ohmyzsh/ohmyzsh/issues/7642#issuecomment-489122630).

**Solution**

Could you please try the following:

```
rm ~/.zcompdump*
source ~/.zshrc
# (optional) restart the terminal
```

**Comment by vcg3rd** [comment]
So, this is embarrassing.  There's a quirky reason related to my dyslexia, poor typing skills, and my specific password for Dnote that I can't explain unless I want to change my password, but saying that if I'm logged in in bash I should be in zsh made me think I must be typing it wrong, and I, in fact was, dozens of times thinking I was doing it right, but I couldn't have been because I copy/pasted and it worked.

So sorry.

However, your autocompletion tip worked perfectly.  Thanks a million!

**Comment by sungwoncho** [comment]
@vcg3rd no worries. Actually that happens to me as well because password inputs are not visible in many linux programs. Please feel free to re-open if issues persist.
