### ISSUE TITLE
No information on how to use a different editor?

### ISSUE THREAD

**Issue by rsolvang** [dnote/dnote#417]
* **Please describe the feature you would like to have.**
I can't find any information about how to set which editor to use with dnote. This should be mentioned either on the website or the Github wiki and maybe also in the CLI help.

* **What alternatives have you considered?**
I tried defining my editor of choice in the .bashrc-file (EDITOR=nano), without success. 

* **Any additional context**
This feature is mentioned prominently on the homepage, without further explanation on how it works.

EDIT: Ok, i finally found out how to do this, but the information is not easy to find. I had to go to the wiki and then click "Guide" – not the most descriptive title :)

**Comment by sungwoncho** [comment]
@rsolvang sorry to hear about the confusion. It is definitely the fault of the project that the instruction for such prominently advertised feature is so hard to find. I will include a link to the wiki in the README.

For people searching for similar issue: please change `editor` in your `.dnote/dnoterc` file.

**Comment by sungwoncho** [comment]
Closed this as fixed by #418 but please feel free to reopen.
