### ISSUE TITLE
Running migrations fail: relation "repetition_rules" does not exist

### ISSUE THREAD

**Issue by shpdnkti** [dnote/dnote#437]
## Environment

* project (cli, server, browser-extension): server by using Docker
* version: dnote/dnote latest
* operating system: Centos 7.6

## Description

goroutine 1 [running]:
main.startCmd()
        /home/sung/dev/dnote-workspace/dnote/pkg/server/main.go:135 +0x4d5
main.main()
        /home/sung/dev/dnote-workspace/dnote/pkg/server/main.go:175 +0x1e8
Waiting for the database connection...
panic: running migrations: running migrations: pq: relation "repetition_rules" does not exist handling 20191028103522-create-weekly-repetition.sql

## Steps to reproduce

Install by using Docker like https://github.com/dnote/dnote/blob/master/host/docker/README.md

**Comment by mrasong** [comment]
same problem by using docker 
version: dnote/dnote latest
OS: macOS 10.15.3 (19D76)

```
dnote_1     | panic: running migrations: running migrations: pq: relation "repetition_rules" does not exist handling 20191028103522-create-weekly-repetition.sql
dnote_1     |
dnote_1     | goroutine 1 [running]:
dnote_1     | main.startCmd()
dnote_1     | 	/home/sung/dev/dnote-workspace/dnote/pkg/server/main.go:135 +0x4d5
dnote_1     | main.main()
dnote_1     | 	/home/sung/dev/dnote-workspace/dnote/pkg/server/main.go:175 +0x1e8
dnote_dnote_1 exited with code 2
```

**Comment by sungwoncho** [comment]
Sorry about that. A fix (#438) has been released in v1.0.1. Could you please pull the latest docker image and try again?

If you are using docker-compose:

```
docker-compose down
docker-compose pull
docker-compose up -d
```

Also, there was an undocumented change in 1.0.0: now users need to set `OnPremise` environment variable to `true` to automatically be upgraded to Dnote Pro when self-hosting. The easiest way to apply this is to pull the latest `docker-compose.yml` file as followes

    curl https://raw.githubusercontent.com/dnote/dnote/master/host/docker/docker-compose.yml > docker-compose.yml

Or simply add the follow key-value pair into your `docker-compose.yml` file:

    OnPremise: "true"

Either way will work.

**Comment by mrasong** [comment]
ok now

**Comment by sungwoncho** [comment]
@mrasong thanks for reporting. Closing now.

**Comment by shpdnkti** [comment]
Thanks
