### ISSUE TITLE
What’s the advantages of a database storage compared to plain files in a directory?

### ISSUE THREAD

**Issue by NightMachinary** [dnote/dnote#464]
I have started migrating my notes to a simple workflow of putting everything in markdown files organized by file paths (and tags that I can grep/fzf on), and I am wondering why most apps are using databases. (Considering a database is pretty useless with standard unix tools.)
So what am I missing?
Btw, screenshots/live demo of DNote’s web interface would help adoption.

**Comment by sungwoncho** [comment]
Hi @NightMachinary, I don't think you're missing anything. Your way of organizing things works well. Some benefits of using database are:

* can use web interface by syncing
* data is portable as a single sqlite file

But if those are not important to the user, they don't need to make the tradeoff.

Thanks, noted your suggestion about live demo. I will close this as it is not an issue but feel free to continue on https://forum.getdnote.com
