### ISSUE TITLE
Mathematics Support

### ISSUE THREAD

**Issue by RyanGreenup** [dnote/dnote#475]
* **Please describe the feature you would like to have.**
An implementation of Mathjax would be really useful (or atleast KaTeX)

* **What alternatives have you considered?**
WikiJS/WizNote/Leanote/Boostnote/Notable/MediaWiki etc.

* **Any additional context**
It shouldn't be hard to implement, it really is as simple as putting this into the *HTML* header and allowing users to run it locally if they desire:

```js
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```

**Comment by sungwoncho** [comment]
I will close this issue because the web client is discontinued (#590).
