### ISSUE TITLE
default book

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#484]
* **Please describe the feature you would like to have.**
Ability to add notes without assigning a book

* **What alternatives have you considered?**
Manually specify books for each note being created

* **Any additional context**
It might be useful to be able to simply create a note without specifying book. Especially when you are on a phone.

Idea:

* Ability to specify default book
* Add a special book 'unassigned' and funnel notes without books to it. Doing so might require change and migration on CLI.

**Comment by bsucker98** [comment]
Just another idea Also it would be cool if we can move notes from one book to another, and if we can add multiple tags to notes

**Comment by sungwoncho** [comment]
Not sure if needed, now that the web client is removed. Please re-open if you have suggestions or ideas.
