### ISSUE TITLE
Social / enterprise login

### ISSUE THREAD

**Issue by colearendt** [dnote/dnote#496]
* **Please describe the feature you would like to have.**

Allow social login (Google, GitHub, etc.) or plugin options (i.e. OAuth2, SAML?) to `dnote` server so easier to share / integrate with others and onboard them into `dnote`. Related to #427 

* **What alternatives have you considered?**

N/A

* **Any additional context**

I love the idea of a shared knowledge base, and shared spaced repetition.

**Comment by sungwoncho** [comment]
The social login used to be supported, but was dropped when Dnote experimented with [end-to-end encryption feature](https://github.com/dnote/dnote/pull/165).

If such feature can significantly improve the ability to share notes and onboard people, I am happy to consider it. But I doubt that it would be the case as password managers are becoming a norm.

> plugin options (i.e. OAuth2, SAML?)

Just curious, how do you see this working in Dnote's context? I don't have much experience with those.

**Comment by colearendt** [comment]
To be completely honest, I'm not 100% certain these are reasonable thoughts 😄 Mostly just brainstorming. The thought I had on social sign-in was to avoid the sign-up process where creating a password is necessary - i.e. if you were to share a book with someone as discussed in #427

As for SAML / OAuth2, the idea there was to have a generic authentication interface so that if a company wanted to run a dnote server in their organization, they could use their company's SSO. This feels like a bit of a stretch so maybe not worth considering 😄

**Comment by sungwoncho** [comment]
While useful, I think that adding this feature would conflict with the project tenets (https://github.com/dnote/dnote/wiki#tenets). Therefore, I will close this issue for now. Please feel free to re-open or continue the discussion.
