### ISSUE TITLE
add emoji support to dnote

### ISSUE THREAD

**Issue by colearendt** [dnote/dnote#497]
* **Please describe the feature you would like to have.**

It would be nice to present emojis `:smile:`, `:sad:`, `:sob:`, etc. in dnote server (or - extra credit - in the CLI with `iterm2`) much like github does.

* **What alternatives have you considered?**

N/A

* **Any additional context**

**Comment by sungwoncho** [comment]
Admittedly, the editor in the web application is rather rudimentary at the moment. It would be cool to support it as we iterate on the editor.

**Comment by sungwoncho** [comment]
Now that the web client has been removed, this feature might be less relevant to the future roadmap. Therefore, I will close this. Please feel free to re-open.
