### ISSUE TITLE
Add fuzzy search

### ISSUE THREAD

**Issue by daganomri** [dnote/dnote#499]
* **Please describe the feature you would like to have.**
Would it be possible to implement some form of fuzzy search? It will make finding notes a lot easier. 

* **What alternatives have you considered?**
Using the current find command. 

* **Any additional context**

**Comment by sungwoncho** [comment]
Thanks @daganomri. Fuzzy search will be definitely useful. I am happy to consider a solution. The only qualm is that it might require scanning all note contents.

Let's discuss over at #415.
