### ISSUE TITLE
Dnote with Pipeline

### ISSUE THREAD

**Issue by anasbousselham** [dnote/dnote#581]
Hi,
It is possible to add a PipeLine func like  `echo bee5af34457c3fafd4f1d | dnote add Hashs --pipe` 
Thank you.

**Comment by sungwoncho** [comment]
Hey @anasbousselham, looks like there has been a similar request in the past, too https://github.com/dnote/dnote/issues/82

Would you find it easier to use if it didn't require `--pipe`? e.g. `echo bee5af34457c3fafd4f1d | dnote add Hashs`

**Comment by anasbousselham** [comment]
I have this when I try you command:
```
echo asasasas |dnote add Hashs                                                                                      1 ⨯
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
  ⨯ getting content: Failed to get editor input: waiting for the editor: exit status 1```

**Comment by sungwoncho** [comment]
@anasbousselham sorry for the confusion, to be clear, it is not currently supported. Just wanted your opinion about if `--pipe` is needed if we do support this in the future.
