### ISSUE TITLE
Customize sqlite file location

### ISSUE THREAD

**Issue by Napuu** [dnote/dnote#585]
Hi, I would appreciate if it was possible to specify custom sqlite file location at `dnoterc`, as I currently use Syncthing to move files between my devices.
Do you think it would fit in to the scope of this project? If so I'd happily implement that and file a PR.

**Comment by sungwoncho** [comment]
Hi @Napuu, currently, you can already control the location of Dnote data directory using `XDG_DATA_HOME` environment variable. (https://github.com/dnote/dnote/blob/master/pkg/cli/dirs/dirs_unix.go#L30, #478)

Does this provide enough flexibility to achieve your requirement?

**Comment by Napuu** [comment]
How did I miss that :D but yeah that's exactly what I meant, thanks!

**Comment by sungwoncho** [comment]
No worries, there is currently no proper documentation for the project. Opened #605
