### ISSUE TITLE
not support  darwin/arm64

### ISSUE THREAD

**Issue by dislazy** [dnote/dnote#606]
~ curl -s https://www.getdnote.com/install | sh

System not supported: darwin/arm64
Please compile manually from https://github.com/dnote/dnote
A problem occurred while installing Dnote. Please report it on https://github.com/dnote/dnote/issues so that we can help you.

**Comment by sungwoncho** [comment]
Hi @dislazy, darwin/arm64 is still not supported. I will track this issue in #572.
