### ISSUE TITLE
allow password pasting when logging into the sync server in the app

### ISSUE THREAD

**Issue by benjaloo** [dnote/dnote#607]
I'm finding dnote fills a niche not easily filled by other software, so thanks.

Please allow password pasting when logging into the sync server in the app

Not allowing this encourages the use of less secure passwords.  Many people (like me) use password vaults like LastPass or KeePass and use long, complex passwords for security.   These must be pasted--they're too long and random to remember and type.

thanks!

**Comment by sungwoncho** [comment]
Hi @benjaloo, sorry for the late response. I agree that users should be allowed to paste in passwords, and that apps that do not allow it encourages less secure password.

I have checked Dnote web app in Mozilla Firefox 110.0.1 and Google Chrome 110.0.5481.100 to verify that it allows to paste in password. If it does not work for you, I can confirm that is not the intention of Dnote and is a bug. Could you try again in the latest server release, and provide information about OS and browser if the issue persists?

**Comment by sungwoncho** [comment]
For now I will resolve this issue due to not being able to reproduce. Could anyone please re-open this issue if I am missing something? Thanks.
