### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by Vainyards** [dnote/dnote#613]
## Environment

* project (cli, server, browser-extension): webinterface, cli and browser extension
* version: 0.12
* operating system: macos ventura

## Description
I cannot open the the notes. just says "page not found"

## Steps to reproduce
write new note in browser and/or cli,
Save/sync
Cannot open note from browser extension.

**Comment by sungwoncho** [comment]
Hi @Vainyards, the web interface has been discontinued from server v2.0.0 (https://www.getdnote.com/blog/simplifying-dnote/). Please feel free to re-open in case you need further clarification.
