### ISSUE TITLE
homebrew install broken

### ISSUE THREAD

**Issue by rhaynes74** [dnote/dnote#645]
Hi folks, I am not sure whose issue this is exactly, but my usual way to install dnote via homebrew seems to be broken.  Deleting the file indicated and trying again doesn't work. 

brew tap dnote/dnote
brew install dnote
==> Fetching dnote/dnote/dnote
==> Downloading https://github.com/dnote/dnote/releases/download/cli-v0.14.0/dno
Already downloaded: /Users/rhaynes74/Library/Caches/Homebrew/downloads/e1615eadfab931302da9bc98e4c7996bae37df3dff7329fdfa310bd7b38b92ba--dnote_0.14.0_darwin_amd64.tar.gz
Error: dnote: SHA256 mismatch
Expected: c34dfd5a7a47e5452a421fe0790d3aa9be5aa1307b95f7e2cff8ca21dee17576
  Actual: 264af0c4726cea5b5ffd48fc50f0a6c09f644f2b053c9266f7c08717deb7c733
    File: /Users/rhaynes74/Library/Caches/Homebrew/downloads/e1615eadfab931302da9bc98e4c7996bae37df3dff7329fdfa310bd7b38b92ba--dnote_0.14.0_darwin_amd64.tar.gz
To retry an incomplete download, remove the file above.

**Comment by sungwoncho** [comment]
Hi @rhaynes74, it was fixed by https://github.com/dnote/homebrew-dnote/commit/d31cb39f5f450dfdf1e1140a4b5a2a8cb994089a. Thanks for the report.
