### ISSUE TITLE
Error relocating dnote, need musl(libc) release

### ISSUE THREAD

**Issue by qaqland** [dnote/dnote#652]
## Environment

* project: cli 
* version: 0.15.0
* operating system: alpine linux 3.18 x86_64

## Description

```
~ $ ldd dnote
        /lib64/ld-linux-x86-64.so.2 (0x7f61a5f78000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f61a5f78000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f61a5f78000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f61a5f78000)
        libresolv.so.2 => /lib/libresolv.so.2 (0x7f61a5f72000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f61a5f78000)
Error relocating dnote: __vfprintf_chk: symbol not found
Error relocating dnote: __memcpy_chk: symbol not found
Error relocating dnote: __res_search: symbol not found
Error relocating dnote: __memset_chk: symbol not found
Error relocating dnote: __fprintf_chk: symbol not found
```

## Steps to reproduce

download https://github.com/dnote/dnote/releases/download/cli-v0.15.0/dnote_0.15.0_linux_amd64.tar.gz unzip and run `ldd dnote`

---

Works(local) well now but ldd shows ERROR!

Maybe need release for musl.

**Comment by sungwoncho** [comment]
Hi @qaqland, would you be able to try the following?

```
apk add --no-cache libc6-compat gcompat
```

I remember getting around similar issue when I was running the server on Alpine linux image (https://github.com/dnote/dnote/blob/master/host/docker/Dockerfile#L7C5-L9C16)

**Comment by qaqland** [comment]
i'm making the port to alpine, everything goes well.

**Comment by sungwoncho** [comment]
Thanks for the update. Could you share your port to alpine?

**Comment by qaqland** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/65787
