### ISSUE TITLE
remove web interface part in makefile

### ISSUE THREAD

**Issue by qaqland** [dnote/dnote#668]
* **Please describe the feature you would like to have.**

It is said here: https://www.getdnote.com/blog/simplifying-dnote/

> From April 11, 2022, Dnote web interface will be removed from the project.

but in Makefile there are still some js and css build

https://github.com/dnote/dnote/blob/bdc980e5ced804f78599d9cdff02cf6d10c9349d/Makefile#L64C1-L65C59

**Comment by sungwoncho** [comment]
Hi @qaqland, thanks for your attention to detail. While it's true that the web interface for managing notes has been removed, there still exists a minimal web interface where users can change password and email. The CSS and JS files are for that website. I will resolve this for now, but please let me know if I can clarify anything.
