### ISSUE TITLE
using the EDITOR environment variable

### ISSUE THREAD

**Issue by ntchambers** [dnote/dnote#72]
Looking through the source, trying to figure out how to set my editor to nano, I discovered the following [method](https://github.com/dnote-io/cli/blob/b1386722a920f2e76860806b0839781e29338f9c/core/core.go#L79-L91). Is there a reason why it only uses the value in `EDITOR` if it recognizes it? I can understand special casing certain editors, however I don't see the reasoning behind ignoring `EDITOR` if it doesn't know it. Most likely the person has either explicitly set `EDITOR` (as in my case) and has it specially configured, or is used to using whatever the OS has set as the default `EDITOR`. I think a more useful way of going about this is something similar to:

```go
func getEditorCommand() string {
	editor := os.Getenv("EDITOR")

	if editor == "" {
		return "vim"
	} else if editor == "atom" {
		return "atom -w"
	} else if editor == "subl" {
		return "subl -n -w"
	} else if editor == "mate" {
		return "mate -w"
	}

	return editor
}
```

A minor sidenote: `vi` is POSIX, whereas `vim` is not, so `vi` is more likely to be installed.

**Comment by sungwoncho** [comment]
The reason for defaulting to `vim` was that commands to launch some editors return immediately, unless a flag is passed (`atom` vs `atom -w`).

We can probably default to `EDITOR`, if we cover editors that require flags as much as possible. I am not totally sure what the best solution is. Any ideas on the trade-off welcomed.

In the meantime you can change the editor following these steps https://github.com/dnote-io/cli/wiki/Guide#change-editor

**Comment by dvnrsn** [comment]
My two cents: set vim as default (mine was nano?) and/or check `$EDITOR`. This took me longer to find than it should have. Thanks for the sweet tool.

**Comment by sungwoncho** [comment]
@dvnrsn thanks for the feedback. By the way, it is defaulting to `vi`. I suspect that your system's `$EDITOR` was set to `nano` (I have noticed this in the past in some fresh ubuntu installations). Please let me know if otherwise.

**Comment by dvnrsn** [comment]
I'm fairly confident my $EDITOR was vim, but my dnote was out of date. Upgraded and good to go. :)

**Comment by sungwoncho** [comment]
@dvnrsn great, thanks for the update.

**Comment by sungwoncho** [comment]
I will close this for now due to inactivity. If anyone finds edge cases or have suggestions, please feel free to comment.

**Comment by riapacheco** [comment]
Hey there -- just got a fresh OS (elementary OS distro) and looking for the steps to change my editor to Nano (changed my default to nano but the dnote editor is vim); but the documentation seems to be missing? https://github.com/dnote/dnote/wiki#change-editor

Can I get a re-direct to where the new documentation is?
